data_dir: /home/subhrangsu/contssl/continuous_ssl_problem/
resume: True
world_size: 1
rank: 0
workers: 64
multiprocessing_distributed: False
distributed: False
dataparallel: False
dist_backend: "gloo"
dist_url: 'tcp://224.66.41.62:23456'
node: 'localhost'
port: 21992
seed: 0
gpu: 0
ngpu: 4
mem_gb: 128
slurm: False
slurm_partition: special
slurm_timeout: 360
print_freq: ${logging.print_freq}
evaluate: False
nodelist: ""
exclude_nodes: ""
